### ISSUE TITLE
Error reading a SampleSheet

### ISSUE THREAD

**Issue by YasirKusay** [umccr/v2-samplesheet-maker#93]
Hi, 
 
I was using your `v2-samplesheet-to-json` script. My `SampleSheet.csv` file has headers that look like this `[Header],,,,,,,` and when I ran the program, I got this traceback: 

```
2024-05-08 13:01:07,703 - ERROR    - samplesheet               - read_from_samplesheet_csv                : LineNo. 358  - Did not get a section name
Traceback (most recent call last):
  File "~/miniconda3/envs/sample_sheet/bin/v2-samplesheet-to-json", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/miniconda3/envs/sample_sheet/lib/python3.12/site-packages/v2_samplesheet_maker/run/v2_samplesheet_reader.py", line 36, in main
    read_v2_samplesheet()
  File "~/miniconda3/envs/sample_sheet/lib/python3.12/site-packages/v2_samplesheet_maker/run/v2_samplesheet_reader.py", line 29, in read_v2_samplesheet
    v2_samplesheet_reader(
  File "~/miniconda3/envs/sample_sheet/lib/python3.12/site-packages/v2_samplesheet_maker/functions/v2_samplesheet_reader.py", line 42, in v2_samplesheet_reader
    samplesheet = SampleSheet.read_from_samplesheet_csv(csv_input_path_or_stream)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/sample_sheet/lib/python3.12/site-packages/v2_samplesheet_maker/classes/samplesheet.py", line 359, in read_from_samplesheet_csv
    raise ValueError
ValueError
```

Looking into the  `v2_samplesheet_maker/classes/samplesheet.py` file, I noticed the `if line.startswith("[") and line.endswith("]"):` condition in line 346 is never hit as my section headers do not end with a "]" and hence, no header is identified, making your program think that my samplesheet has no section headers.

**Comment by alexiswl** [comment]
Hi @YasirKusay, great to see that someone else is using this! Are you able to provide a copy of your samplesheet (truncated and anonymous is fine), that reproduces this error and I'll make a fix for it

**Comment by YasirKusay** [comment]
```
[Header],,,,
IEMFileVersion,4,,,
InvestigatorName,NoOne,,,
ProjectName,Sequences,,,
Date,01/03/2021,,,
Workflow,GenerateFASTQ,,,
Application,FASTQ Only,,,
Assay,Nextera,,,
Description,Sequencing,,,
Chemistry,Amplicon,,,
,,,,
[Reads],,,,
151,,,,
151,,,,
,,,,
[Settings],,,,
ReverseComplement,0,,,
Adapter,CTGTCTCTTATACACATCT,,,
,,,,
[Data],,,,
Sample_ID,Sample_Name,I7_Index_ID,index,I5_Index_ID,index2
1,DG-1-A01,i7A01,GTACGTCA,i5A01,GAGGTAGT
```

I used the above, which was based on: https://github.com/YamamotoLabUCSF/SampleSheet/blob/master/SampleFiles/ExampleSampleSheet.csv

**Comment by alexiswl** [comment]
Hi @YasirKusay, 

The good news this is resolved! 

The less good news is that I note that you're using a v1 samplesheet instead of a v2 samplesheet. This is going to cause some issues.  

There are some differences between v1 and v2 samplesheets and wish there were better resources documenting this.  
All I can really point you to is this - https://support-docs.illumina.com/SHARE/SampleSheetv2/Content/SHARE/SampleSheetv2/Parameters.htm

In order to get this script to work for you I had to make the following changes.  

```bash
diff SampleSheet.old.csv SampleSheet.new.csv
```

<details>
<summary>SampleSheet.new.csv</summary>

```csv
[Header],,,,
IEMFileVersion,4,,,
InvestigatorName,NoOne,,,
ProjectName,Sequences,,,
Date,01/03/2021,,,
Workflow,GenerateFASTQ,,,
Application,FASTQ Only,,,
Assay,Nextera,,,
Description,Sequencing,,,
Chemistry,Amplicon,,,
,,,,
[Reads],,,,
Read1Cycles,151,,,,
Read2Cycles,151,,,,
,,,,
[BCLConvert_Settings],,,,
ReverseComplement,0,,,
Adapter,CTGTCTCTTATACACATCT,,,
,,,,
[BCLConvert_Data],,,,
Sample_ID,Sample_Name,I7_Index_ID,index,I5_Index_ID,index2
1,DG-1-A01,i7A01,GTACGTCA,i5A01,GAGGTAGT
```

</details>

```
< 151,,,,
< 151,,,,
---
> Read1Cycles,151,,,,
> Read2Cycles,151,,,,
16,17c16
< [Settings],,,,
< ReverseComplement,0,,,
---
> [BCLConvert_Settings],,,,
20c19
< [Data],,,,
---
> [BCLConvert_Data],,,,
```

```bash
v2-samplesheet-to-json SampleSheet.new.csv - 2>/dev/null
```

Will get you the following json

```
{
  "header": {},
  "reads": {
    "read_1_cycles": 151,
    "read_2_cycles": 151
  },
  "bclconvert_settings": {},
  "bclconvert_data": [
    {
      "sample_id": "1",
      "index": "GTACGTCA",
      "index2": "GAGGTAGT",
      "sample_name": "DG-1-A01"
    }
  ]
}
```

In order to maintain a lot of the information you've provided in the header and settings, we'll need to migrate over a few of the keys to the accepted list (which was set according to the resources above).

* Adapter -> AdapterRead1 + AdapterRead2
* ReverseComplement is now set in the RunInfo.xml file
* i7IndexId and i5IndexId no longer part of BCLConvert_Data settings
* Set FileFormatVersion, RunName and RunDescription in the header section

<details>
<summary>New Csv</summary>

```csv
[Header],,,,
RunName,Sequences,,,
RunDescription,Sequencing,,,
FileFormatVersion,2,,,
,,,,
[Reads],,,,
Read1Cycles,151,,,,
Read2Cycles,151,,,,
,,,,
[BCLConvert_Settings],,,,
AdapterRead1,CTGTCTCTTATACACATCT,,,
AdapterRead2,CTGTCTCTTATACACATCT,,,
,,,,
[BCLConvert_Data],,,,
Sample_ID,Sample_Name,Index,Index2,
1,DG-1-A01,GTACGTCA,GAGGTAGT,
```

</details>

<details>
<summary>Output JSON</summary>

```json
{
  "header": {
    "file_format_version": 2,
    "run_name": "Sequences",
    "run_description": "Sequencing"
  },
  "reads": {
    "read_1_cycles": 151,
    "read_2_cycles": 151
  },
  "bclconvert_settings": {
    "adapter_read_1": "CTGTCTCTTATACACATCT",
    "adapter_read_2": "CTGTCTCTTATACACATCT"
  },
  "bclconvert_data": [
    {
      "sample_id": "1",
      "index": "GTACGTCA",
      "index2": "GAGGTAGT",
      "sample_name": "DG-1-A01"
    }
  ]
}
```

</details>

**Comment by YasirKusay** [comment]
Thank you for the very quick response and thank you for the reply, it was been very helpful! I this also explains this error:

```
Traceback (most recent call last):
  File "~/miniconda3/envs/sample_sheet/bin/v2-samplesheet-to-json", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/miniconda3/envs/sample_sheet/lib/python3.12/site-packages/v2_samplesheet_maker/run/v2_samplesheet_reader.py", line 36, in main
    read_v2_samplesheet()
  File "~/miniconda3/envs/sample_sheet/lib/python3.12/site-packages/v2_samplesheet_maker/run/v2_samplesheet_reader.py", line 29, in read_v2_samplesheet
    v2_samplesheet_reader(
  File "~/miniconda3/envs/sample_sheet/lib/python3.12/site-packages/v2_samplesheet_maker/functions/v2_samplesheet_reader.py", line 42, in v2_samplesheet_reader
    samplesheet = SampleSheet.read_from_samplesheet_csv(csv_input_path_or_stream)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/sample_sheet/lib/python3.12/site-packages/v2_samplesheet_maker/classes/samplesheet.py", line 417, in read_from_samplesheet_csv
    return cls(samplesheet_dict_sanitised)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/miniconda3/envs/sample_sheet/lib/python3.12/site-packages/v2_samplesheet_maker/classes/samplesheet.py", line 130, in __init__
    sections_dict_as_list = sorted(
                            ^^^^^^^
  File "~/miniconda3/envs/sample_sheet/lib/python3.12/site-packages/v2_samplesheet_maker/classes/samplesheet.py", line 138, in <lambda>
    key=lambda x: class_headers_as_list.index(get_stripped_section_name(list(x.keys())[0]))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 'settings' is not in list
```

I am also using this program to determine if a bunch of samplesheets that I am working with are in the v2 format, and the error I am getting here clearly indicates that this samplesheet was not in that format.
